language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0

env:
  - COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
  - COMPOSER_FLAGS="--prefer-stable"

cache:
  directories:
    - ./vendor
    - $HOME/.composer/cache

before_script:
  - composer self-update
  - composer require phpunit/phpunit --dev --no-update
  - composer remove friendsofphp/php-cs-fixer --dev --no-update
  - |
    if php -r 'exit((int)!version_compare(PHP_VERSION, "7.4", ">="));'; then
      composer require doctrine/orm:^2.6.4 $COMPOSER_FLAGS --no-update
    elif php -r 'exit((int)!version_compare(PHP_VERSION, "7.3", ">="));'; then
      composer require doctrine/orm:^2.6.3 $COMPOSER_FLAGS --no-update
    else
      composer require doctrine/orm:^2.4.5 $COMPOSER_FLAGS --no-update
    fi
  - |
    if php -r 'exit((int)!version_compare(PHP_VERSION, "7.1", "<"));'; then
      composer remove doctrine/cache --dev --no-update
    fi
  - composer update $COMPOSER_FLAGS
  - composer show | grep -E '^(doctrine/|lampager/)'
  - mkdir -p build/logs

script:
  - php -dxdebug.mode=coverage vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/coveralls
