name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [5.6, 7.0, 7.1, 7.2, 7.3, 7.4, 8.0]
        composer_flags:
          - --prefer-stable --prefer-lowest
          - --prefer-stable

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug

      - name: Adjust package versions
        run: |
          composer require phpunit/phpunit --dev --no-update
          composer remove friendsofphp/php-cs-fixer --dev --no-update
          if php -r 'exit((int)!version_compare(PHP_VERSION, "7.4", ">="));'; then
            composer require doctrine/orm:^2.6.4 ${{ matrix.composer_flags }} --no-update
          elif php -r 'exit((int)!version_compare(PHP_VERSION, "7.3", ">="));'; then
            composer require doctrine/orm:^2.6.3 ${{ matrix.composer_flags }} --no-update
          else
            composer require doctrine/orm:^2.4.5 ${{ matrix.composer_flags }} --no-update
          fi
          if php -r 'exit((int)!version_compare(PHP_VERSION, "7.1", "<"));'; then
            composer remove doctrine/cache --dev --no-update
          fi
          composer update ${{ matrix.composer_flags }}

      - name: Display package versions
        id: package-versions
        run: |
          composer show | grep -E '^(doctrine/|lampager/)'
          echo '::set-output name=doctrine::'$(composer show | grep -E '^(doctrine/orm)' | awk '{print $2}')

      - run: mkdir -p build/logs
      - run: vendor/bin/phpunit --coverage-clover build/logs/clover.xml

      - name: Upload Coverage
        uses: nick-invision/retry@v2
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_PARALLEL: 'true'
          COVERALLS_FLAG_NAME: 'php:${{ matrix.php }} doctrine:${{ steps.package-versions.outputs.doctrine }}'
        with:
          timeout_minutes: 1
          max_attempts: 3
          command: |
            composer global require php-coveralls/php-coveralls
            php-coveralls --coverage_clover=build/logs/clover.xml -v

  coverage-aggregation:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Aggregate Coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
